language: node_js
node_js:
- '6.2'
cache:
  directories:
  - node_modules
  - "$HOME/.npm"
  - "$HOME/.gem"
before_install:
- npm install -g gulp
script:
- gulp test
- gulp
deploy:
  provider: npm
  email: me@brianneisler.com
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: WK9rhQ54kWUkFVLYK4sehNGi9Tksmpv0PxaBS2sjyW+Px0g0sJb/kEX/jcbWyJlSHb5fbZWFZzRIBNkG+7Gt6449oXmzCWTvmP59xr2PTQUO6MXgruHizSo5r7xSmh0vMsPsn+SvWdSktI/TR703Vg6Dxs5rApMSNmkGZJ5+DrBBmceCRIMpGm4y7/Zzq8bNNiA2qaPorEZvkWprs6XAdB8eB3cxOaKoDJb3W/UIj0SXz54ZaTNPl4/xQzXP7I1PkQLbC8j1IG3Eo1SOU4ixEHlhHycbkcxjuGclJdGVb1NkRxTj5K0iBlTfaToP6KI/MVOXujgho1/lR/D2+7+zW31jU/j4VazNYW2wBdQFPQochCWpddvIJmSmIoCvR/hfC+1bVWzIUzYERS6+Ysp394C6R39qRmSx1dAuUO2MWGbkI2fXxh7Gec8df2+zZd13iK9uBlpLO3Uok2FdkHQjY5ZLrBtwgZZE2OXZuxUftmrSUhbEt6H7KWJaj9pQdhKbpEdvSp+C2xz7z78DvnVTHJXGxbhbbwGesONrU7bPen9DxyawqHfOab6x1fsdcrS5IRjYy0oJ8lkXUIxy2KCZo5nMjL1F3RQZYJpNXlfeFFp9kdEBs4TOrldjy/nMyDAAAx8Wk32Jzua26lzFQf8eAQa59odpmAPgX9VbEe5CLhg=
